name: home-stack

include:
  - path: ./core/postgres.yml
  - path: ./apps/keycloak.yml
  - path: ./apps/pgadmin.yml
  - path: ./apps/n8n.yml
  - path: ./apps/nginx-proxy-manager.yml

networks:
  infra-network:
    name: local-infra-network
    driver: bridge

volumes:
  postgres-data:
    name: local-postgres-data
  n8n-data:
    name: local-n8n-data
  npm-data:
    name: local-npm-data
  npm-letsencrypt:
    name: local-npm-letsencrypt
  kc-data:
    name: local-kc-data
  pgadmin-data:
    name: local-pgadmin-data
