name: home-stack

include:
  - path: ./services/nginx.yml
  - path: ./core/postgres.yml
  - path: ./core/redis.yml
  - path: ./apps/keycloak.yml
  - path: ./apps/pgadmin.yml
  - path: ./apps/redis-commander.yml

networks:
  infra-network:
    name: home-stack-infra
    driver: bridge

volumes:
  postgres-data:
    name: home-stack-postgres-data
  keycloak-data:
    name: home-stack-keycloak-data
  pgadmin-data:
    name: home-stack-pgadmin-data
  redis-data:
    name: home-stack-redis-data
