map $ssl_preread_protocol $port_443_backend {
    "" host_ssh_backend;
    default local_https_backend;
}

upstream local_https_backend {
    server 127.0.0.1:8443;
}

upstream host_ssh_backend {
    server host.docker.internal:22;
}

server {
    listen 443;
    proxy_pass $port_443_backend;
    ssl_preread on;
    proxy_connect_timeout 5s;
    proxy_timeout 1h;
}

upstream postgres_backend {
    server postgres:5432;
}

server {
    listen 5432;
    proxy_pass postgres_backend;
    proxy_connect_timeout 5s;
    proxy_timeout 1h;
}

upstream redis_backend {
    server redis:6379;
}

server {
    listen 6379;
    proxy_pass redis_backend;
    proxy_connect_timeout 5s;
    proxy_timeout 1h;
}
