upstream postgres_backend {
    server postgres:5432;
}

server {
    listen 5432;
    proxy_pass postgres_backend;
    proxy_connect_timeout 5s;
    proxy_timeout 1h;
}

upstream redis_backend {
    server redis:6379;
}

server {
    listen 6379;
    proxy_pass redis_backend;
    proxy_connect_timeout 5s;
    proxy_timeout 1h;
}
